import { local } from "../utils/helpers.js";

const words_dict = [
    "May the soul be healed of distress and distress - The body recovers from weakness and fatigue",
    "How often we overcome the days of suffering - We believe that the joy of living is in victory",
    "To my death my feet walked.",
    "Today is wine, tomorrow is an order.",
    "Winds blow counter to what ships desire.",
    "Your compassion, some evil is lesser than others.",
    "I cried for a long time, but when I became someone else, I cried for him.",
    "A blameworthy Lord who has no fault.",
    "He was killed, may God have mercy on him” better than “He fled, may God disgrace him”.",
    "Your brother, your brother. He who has no brother is like someone rushing to hell without a weapon.",
    "Your brother is the one who gives you sincere advice.",
    "If you venture into the honor of Merum, do not be content with anything less than the stars.",
    "If only the teeth are installed, then the forced person has no choice but to ride them.",
    "Happiness and contentment are great cosmetic tools, and deceptive tools for maintaining a youthful appearance.",
    "Decorating the body is faster than decorating the soul.",
    "The strongest cow is not the mooing, it is the cow that is the most mooing.",
    "He who does not know how to pretend does not know how to live.",
    "What is the benefit of a wide world, if your shoes are narrow?.",
    "Calling for freedom does not mean calling for unruliness, chaos, and barbarism. Freedom is a great value, but it is the rule: You are free as long as you are not harmed.",
    "If freedom is weakly armed, we must arm it with willpower.",
    "Receiving death is better than avoiding it.",
    "Honor yourself from every vile thing.",
    "Excessive humility brings humiliation.",
    "Being good to oneself is the ultimate goal of goodness.",
    "The sword is more terrible than anything seen drawn.",
    "Pride is in the forelocks of horses.",
    "The butcher is not intimidated by the large number of sheep.",
    "The mosquito bleeds the lions eye.",
    "The coward will die from above.",
    "The dirt hurts the eyes a little, and the mosquitoes may even hurt the elephant.",
    "I am great for her and for everyone.",
    "I was proud of myself, not of my grandfathers.",
    "Free starve or eat Butdiera.",
    "Wolves attack those who have no dogs and fear the guardian force of the mustanfar.",
    "Humiliation of the one who has no sword.",
    "Live dearly or die generously.",
    "Maybe a shoe is worse than a shoe.",
    "A summer cloud blown by the wind in the morning. The people praise the secret.",
    "There is water in my mouth. Can someone who has water in his mouth speak?.",
    "Do not complain to a person, lest you gloat over him like a wounded person complains to crows and crows.",
    "Common ducklings.",
    "Like Father, Like Son.",
    "This cub is from that lion.",
    "As the noble ascends, he becomes humble, and as the lowly ascends, he becomes arrogant.",
    "There is no dignity like humility and no honor like knowledge.",
    "If the right believer is found, all the reasons for success will be found with him.",
    "When a believer is hungry, he is patient, and when he is full, he is grateful.",
    "The believer is ungrateful and the ungodly is mean.",
    "I must invent a system or I will be enslaved by another mans system.",
    "Where order we find food, where chaos finds hunger.",
    "The best way to destroy the capitalist system is to destroy the value of money.",
    "Management works through the system, while leadership works above the system.",
    "Beautiful garnish covers lean meat.",
    "Freedom is not the absence of obligations, but rather the ability to choose what is best for me and commit myself to it.",
    "Life isnt fair, get used to it.",
    "In school they teach you the lesson and then test you, but life tests you and then teaches you the lesson.",
    "Dont be a head, because the head hurts a lot.",
    "There is no dignity for a prophet in his homeland.",
    "If you do not repeatedly drink from the filth, you will become thirsty, and which people will clear their drinks?.",
    "If patience is bitter, its outcome is sweet.",
    "Be patient and get it.",
    "Be patient a little, because after hardship there is ease, and every matter has time and management.",
    "Be patient for every calamity and hardship, and know that eternity is not eternal.",
    "These days. Slowness is from the Most Gracious and haste is from Satan.",
    "Being alarmed by a calamity is a disaster.",
    "Ophthalmia is easier than blindness.",
    "Patience is patient: Be patient with what you hate and be patient with what you love.",
    "Patience at the first shock.",
    "Patience is the key to relief.",
    "The sky is hoped for when it is hidden.",
    "God waits but does not neglect.",
    "Tomorrow is near.",
    "With today comes tomorrow, Masada.",
    "I am drowning, so what is my fear of getting wet?. Slowly you realize opportunities.",
    "Every neighborhood has a deadline.",
    "Every disease has a cure.",
    "If you mention a wolf, be careful.",
    "Another life is death.",
    "If the face becomes less, his modesty decreases, and there is no good in the face if his face becomes less.",
    "If the judiciary comes, the space becomes narrow.",
    "If you are safe from the lion, do not aspire to hunt him.",
    "If you do wrong to those below you, you will not be safe from punishment from those above you.",
    "If your hand is short of reward, let your tongue express gratitude.",
    "If speech is silver, silence is gold.",
    "Some dreams are humiliating.",
    "One hand does not hold two watermelons.",
    "Take wisdom from the mouths of simple people.",
    "Not everything that is known is said.",
    "Sit where your hand is taken and you will be acquitted, and do not sit where your foot is taken and you will be dragged..",
    "Be good to people and you will enslave their hearts. The smarter you get the less you speak.",
    "Every stranger has a relative.",
    "Give your friend your blood and money.",
    "The injustice of a friend is scoundrel.",
    "Beware of your enemy once and your friend a thousand times. If the friend turns away, he knows the harm.",
    "He is the brother of the worthy and the friend of the enemies.",
    "Your brother is the one who believes you, not the one who believes you.",
    "The best of the brothers is the oldest.",
    "If affection is maintained, its interior will be better than its exterior.",
    "If you blame your friend in all matters, you will not find someone you do not blame.",
    "Know your friend and leave him.",
    "The emirate is bitter for breastfeeding and bitter for weaning.",
    "The neighbor has the right of pre-emption.",
    "Neighbor before home.",
    "A friend can either benefit or intercede.",
    "a friend in need is a friend indeed.",
    "Reproach is a gift for loved ones.",
    "The absent person has his excuse with him.",
    "In ethics treasures livelihoods capacity.",
    "Be sincere in your work and reach your fullest potential.",
    "A drowning man clutches at a straw.",
    "Spend what is in your pocket, and what is in the unseen will come to you.",
    "He who taught his son when he was young pleased him when he was old.",
    "Flog the saddle to make the donkey think.",
    "He who exhausted me taught me strength.",
    "Of a young man caught on something on it.",
    "In caution safety in haste repentance.",
    "The calves are wrong even if they are king, and the careful person is right even if they perish.",
    "Whoever stumbles the most quickly.",
    "whoever deliberates in his works gets whatever he looking for.",
    "The error increased calves.",
    "Slowly, demands become easier.",
    "Whoever rides the wheel will make a mistake.",
    "What goes up, must come down.",
    "Only every lowly person is arrogant, and only every high person is humble.",
    "Oh God, protect me from the evil of my friends, but as for my enemies, I am responsible for them.",
    "people to each other.",
    "Unity is better than a bad Gillies.",
    "Your brother is the one who comforted you.",
    "If a world slips, a world will slip due to its slip.",
    "If you get hit and it hurts, the blame is the same.",
    "If you have an opinion, be determined.",
    "If opinion is championed, passion is invalidated.",
    "Send a wise man and do not recommend him.",
    "The crisis is intensifying, and it will be relieved.",
    "The most intense struggle is the struggle against anger.",
    "The most extreme want is lack of reason.",
    "Happiness is good health and bad memory.",
    "Propose to your daughter but not to your son.",
    "A day older than you, he knows you by a year.",
    "A mother is a school, if you prepare her, you prepare a people of good ethnicity.",
    "The stomach does not give birth to an enemy.",
    "Experiences have no end and one continues to increase.",
    "Experience is great science.",
    "The slave knocks with a stick, and the free sign is sufficient for him.",
    "Blame on looking.",
    "Knowledge is beautiful, so be an earner of knowledge and be a student of it as long as you live, citing.",
    "Knowledge is useful and will last forever for the boy, while money will fade away, even if it is useful for a while.",
    "Knowledge raises a house that has no pillars, while ignorance destroys a house of pride and honor.",
    "A monkey in its mothers eyes is a deer.",
    "The book reads from its title.",
    "If you crawl on the woman’s side of a pyramid, then amusement and flirtation will keep you away.",
    "If he knew the reason, the hero of wonder.",
    "If the souls are old, they become tired of wanting bodies.",
    "Seek knowledge from the sciences that will benefit you, negate harm and defect, and then elevate you.",
    "The fairest witnesses are experiences.",
    "Dearer than the boy, the boy was born.",
    "The dearest place in the world is a swimming saddle, and the best companion in time is a book.",
    "A servant of two masters lies to one of them.",
    "If you hear a man saying something good about you that you do not have, do not be sure that he will say something evil about you that you do not have.",
    "Miserliness humiliated the necks of men.",
    "I see every human being who sees the faults of others and is blind to his own fault.",
    "He misheard and responded incorrectly.",
    "I am a lion and an ostrich in wars.",
    "I teach him archery every day, but when he became angry, he helped him shoot at me.",
    "The richest of the rich are those who are not captive by miserliness.",
    "The bane of lying. The least happy people are the envious.",
    "They ate my goodness and disobeyed my command.",
    "The miser is great and has little morals.",
    "The misers wealth is poverty and his kitchen is desert.",
    "A miser does not let one hand wet the other.",
    "Avoid associating with a liar, and if you have to, do not believe him.",
    "People are ignorant of who was the ruler’s oppressor and the Brotherhood’s humiliator.",
    "People brought an answer who did not get angry.",
    "Their conception mixed with their arrows.",
    "If the sheep are dispersed, the mangy goats lead them.",
    "If a persons action is bad, his suspicions will become bad and he will believe his usual delusion.",
    "If he asks, he hesitates, and if he is asked, he procrastinates.",
    "Dig a well, plug a well, and do not idle a worker.",
    "Save your white penny for your black day.",
    "If you are an anvil, be patient, and if you are a hammer, be more painful.",
    "If the wind blows, take advantage of it.",
    "Cover your brothers nakedness because he knows about you.",
    "Thank those who have bestowed blessings upon you, and bestow blessings upon those who thank you.",
    "Strike while the iron is hot.",
    "Make sense of it and trust.",
    "Do good and throw it into the sea.",
    "The best kindness is to be shown without question.",
    "Reduce your reproach, for survival is short, and time changes at times and tends.",
    "Get up immediately, rejoicing, for that is the first degree of success.",
    "When the phone rings, smile while you receive the phone. Your interlocutor on the other end will see your smile through the tone of your voice..",
    "Marry someone who is good at conversation. When you get older, you will realize the importance of that, when talking to the one you love becomes your top priority and interest..",
    "If you love someone, go up to them and say that you love them, unless you dont really mean what you say ! Because he will know the truth just by looking in your eyes.",
    "Do not hesitate to say sorry to the one you wronged, and look into his eyes as you say the words of apology, so that he can read them in your eyes while hearing them with his ears..",
    "Do not judge a person by his relatives alone, as a person did not choose his parents, let alone his relatives.",
    "When you dont want to answer a question, smile at the questioner and say:: Do you think its really important?.",
    "Do not let small things destroy your precious friendship with others. True friendship is a crown on people’s heads that only those who live in empty walls and empty hearts can realize..",
    "Do not make fun of others and their beautiful, rosy dreams, especially those who you believe are less simple and good than you. Perhaps your servant’s status with God is higher and higher than yours and that of many high-ranking people, and you may enjoy their intercession on the Day of Resurrection. Do not underestimate dreams, for the world without them is a dry and boring journey. No matter how beautiful the reality is.",
    "Think a lot, conclude a long time, talk little, and do not neglect everything you hear ! It is certain that you will need in the future.",
    "He who drowns clings to a stick of straw.",
    "Single for a lifetime and not a widow for a month.",
    "Give me life and throw me into the sea.",
    "Except everything that is coming is near, and the earth has a share for every living thing.",
    "The pebble from the mountain.",
    "Morning is rabah.",
    "Age is one and God is one.",
    "What is hoped for is better than what is eaten.",
    "The first tree is a seed.",
    "Out of sight from the heart of the eye.",
    "love is blind.",
    "He who loves his child has mercy on orphans.",
    "Hearts together.",
    "The eyes that have poplars at the end of them killed us and then did not revive our dead. They strike the core until it cannot move. They are the weakest human beings God has created..",
    "The first tree is a seed.",
    "Your Lord is the Lord of hearts.",
    "A little love through reason is good, while a lot of love through ignorance is corrupt.",
    "Do not be afraid what made your longings .. Explain your passion, for we are all lovers.",
    "The mirror of love is blind.",
    "From heart to heart messenger.",
    "A distant Lord is more beneficial than a near one.",
    "I wish the youth would come back one day and tell him what the old man did.",
    "You all asked for a catch.",
    "How far has passed and how close is what is coming.",
    "Whatever one wishes to achieve, the winds blow in a way that ships do not desire.",
    "Every rope is on its end.",
    "What is like night to yesterday.",
    "Heavier than a mountain.",
    "Beware of the crow.",
    "Guard more than a dog.",
    "Inferior to the jugular vein.",
    "Cheaper than dates in Basra.",
    "Faster than the wind.",
    "Closer than the tongue to the teeth.",
    "Distance is estrangement.",
    "Whiteness is half the beauty.",
    "Water is less present and more precious is missing.",
    "An arrogant person is like someone standing on a mountain who sees people as small and they see himself as small.",
    "I follow from the shadows.",
    "Its more like a date with a date.",
    "The stirrups carried him.",
    "Things are back to normal.",
    "The face is as white as the morning, and the hair is as black as the night.",
    "The eyes do not praise every smile, nor does every face frown and rebuke.",
    "A persons tongue is one of the servants of the heart.",
    "The right holder has a strong eye.",
    "Circles revolve around the baggage.",
    "As you condemn, you will be condemned.",
    "fight fire with fire.",
    "Whoever pardons the injustice of his servants out of piety, God’s kindness will come to him out of piety.",
    "This is that and the beginning is darker.",
    "It is the soul that you have not burdened it with, and for eternity there are days of injustice and injustice.",
    "What is like night to yesterday.",
    "He who is afraid of getting wet does not fish.",
    "Most fires come from tiny sparks.",
    "Let evil leave you.",
    "Beware of the fool and beware of his friendliness, for the fool is like a moral garment.",
    "Beware of those whose goodness is not hoped for and whose evil is not safe.",
    "When the time comes, the eye will be sore.",
    "If you mention the wolf, return the stick to him.",
    "If you see the lions teeth prominent, do not think that the lion is smiling.",
    "If you have an opinion, be advised, for the corruption of an opinion is if you hesitate.",
    "Prepare for the bad dog an equivalent dog.",
    "Reduce your food and find your sleep.",
    "Eternity is two bittersweet days.",
    "Whoever is afraid of the goblin will come to him.",
    "The horse may stumble.",
    "The compassionate person is fond of bad thoughts.",
    "If you are a wind, you have encountered a hurricane.",
    "Behind the hill is what lies beyond it.",
    "Take him to death until he is satisfied with the fever.",
    "The drunkenness went away and the idea came.",
    "Days will show you how ignorant you were.",
    "It may come out of a shell that is not a pearl.",
    "He borrowed a pot.",
    "If one of the opponents comes to you with his eye gouged out, do not make up for it until his opponent comes to you, for perhaps his eyes have been gouged out..",
    "If he undertakes a contract and its provisions.",
    "Retribution of the work type.",
    "Right is a state and wrong is round.",
    "Returning to the truth is better than persisting in falsehood.",
    "The rational person does not invalidate a right nor does he invalidate a wrong.",
    "Justice is the basis of ruling.",
    "An eye for an eye and a tooth for a tooth.",
    "If you want to be obeyed, command as much as possible.",
    "If a person does not defile his honor with meanness, then every garment he wears is beautiful.",
    "If you honor the generous, you will control him, and if you honor the mean, he will rebel.",
    "It is enough for a person to count his faults.",
    "If water is present, tayammum is invalid.",
    "Malm ashamed, then do whatever you want.",
    "The purest people have the best morals.",
    "I know people in God Ordahm what God has for him.",
    "Feel disgusted about what Ogillk what Oarzak.",
    "Best generosity tender before the deadline.",
    "Humans are indicative of generosity.",
    "Arrogance over the arrogant is humility.",
    "Humility is one of the traps of honor.",
    "Quality of existing.",
    "The heat is enough for a sign.",
    "Forbearance is the master of morals.",
    "Evidencing good as actors.",
    "Kindness to the offender is reproach.",
    "The secret is honesty.",
    "When the noble becomes pious, he becomes humble, and the lowly, when he becomes pious, becomes arrogant.",
    "The people who changed the world were the people who kept searching when it seemed impossible to others.",
];

export default (className) =>
    Widget.Label({
        className: className || "saying-wd-label",
        // label: "SUIII",
        justification: local === "RTL" ? "left" : "right",
        // truncate: 'end',
        xalign: 0,
        maxWidthChars: 24,
        wrap: true,
    }).poll(30 * 1000 * 60, (self) => {
        const randomIndex = Math.floor(Math.random() * words_dict.length);

        // Use the random index to get a random element
        const randomSaying = words_dict[randomIndex];

        self.label = randomSaying;
    });
